[server]
headless = true
port = 8080
enableCORS = false
maxUploadSize = 900
maxMessageSize = 900

[theme]
# Możesz dodać tutaj ustawienia tematu, np.:
# primaryColor = "#1E90FF"
# backgroundColor = "#F0F2F6"
# textColor = "#000000"


