site_name: Analiza marketingowa
site_url: https://twojadomena.pl
theme:
  name: material
nav:
  - Home: index.md
  - Analiza: analiza_marketingowa.md
  - Modele: modele_marketingowe.md
  - Wyniki: wyniki_analiz.md
  - Wnioski: wnioski.md
